using FoSouzaDev.FinancialControl.Application.DataTransferObjects;
using FoSouzaDev.FinancialControl.Application.Services.Interfaces.Base;

namespace FoSouzaDev.FinancialControl.Application.Services.Interfaces;

public interface IFinancialMovementCategoryAppService : IAllActionsAppService<AddFinancialMovementCategoryDto, GetFinancialMovementCategoryDto, UpdateFinancialMovementCategoryDto>
{
}