using FoSouzaDev.FinancialControl.Application.DataTransferObjects;

namespace FoSouzaDev.FinancialControl.Application.Services.Interfaces;

public interface IFinancialMovementCategoryAppService : IAllActionsAppService<AddFinancialMovementCategoryDto, GetFinancialMovementCategoryDto, UpdateFinancialMovementCategoryDto>
{
}